# Service do mongodb
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-mongodb
  ports:
    - port: 27017
  type: ClusterIP