# Deploy do MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-mongodb
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:{{ .Values.mongodb.imageTag }}
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.mongodb.user }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.mongodb.password }}